export const CHAPTER_DETAILS = {
  1: { latin: 'Al-Fatihah', arabic: 'الفَاتِحَة', meaning: 'Pembukaan', ayat: 7 },
  2: { latin: 'Al-Baqarah', arabic: 'البَقَرَة', meaning: 'Sapi Betina', ayat: 286 },
  3: { latin: "Ali 'Imran", arabic: 'آل عِمْرَان', meaning: "Keluarga 'Imran", ayat: 200 },
  4: { latin: "An-Nisa'", arabic: 'النِّسَاء', meaning: 'Wanita', ayat: 176 },
  5: { latin: "Al-Ma'idah", arabic: 'المَائِدَة', meaning: 'Hidangan', ayat: 120 },
  6: { latin: "Al-An'am", arabic: 'الأَنْعَام', meaning: 'Hewan Ternak', ayat: 165 },
  7: { latin: "Al-A'raf", arabic: 'الأَعْرَاف', meaning: 'Tempat Tertinggi', ayat: 206 },
  8: { latin: 'Al-Anfal', arabic: 'الأَنْفَال', meaning: 'Rampasan Perang', ayat: 75 },
  9: { latin: 'At-Tawbah', arabic: 'التَّوْبَة', meaning: 'Pengampunan', ayat: 129 },
  10: { latin: 'Yunus', arabic: 'يُونُس', meaning: 'Nabi Yunus', ayat: 109 },
  11: { latin: 'Hud', arabic: 'هُود', meaning: 'Nabi Hud', ayat: 123 },
  12: { latin: 'Yusuf', arabic: 'يُوسُف', meaning: 'Nabi Yusuf', ayat: 111 },
  13: { latin: "Ar-Ra'd", arabic: 'الرَّعْد', meaning: 'Guruh', ayat: 43 },
  14: { latin: 'Ibrahim', arabic: 'إِبْرَاهِيم', meaning: 'Nabi Ibrahim', ayat: 52 },
  15: { latin: 'Al-Hijr', arabic: 'الحِجْر', meaning: 'Gunung Al Hijr', ayat: 99 },
  16: { latin: 'An-Nahl', arabic: 'النَّحْل', meaning: 'Lebah', ayat: 128 },
  17: { latin: "Al-Isra'", arabic: 'الإِسْرَاء', meaning: 'Perjalanan Malam', ayat: 111 },
  18: { latin: 'Al-Kahf', arabic: 'الكَهْف', meaning: 'Penghuni Gua', ayat: 110 },
  19: { latin: 'Maryam', arabic: 'مَرْيَم', meaning: 'Maryam', ayat: 98 },
  20: { latin: 'Taha', arabic: 'طه', meaning: 'Thaha', ayat: 135 },
  21: { latin: "Al-Anbiya'", arabic: 'الأَنْبِيَاء', meaning: 'Para Nabi', ayat: 112 },
  22: { latin: 'Al-Hajj', arabic: 'الحَجّ', meaning: 'Haji', ayat: 78 },
  23: { latin: "Al-Mu'minun", arabic: 'المُؤْمِنُون', meaning: 'Orang-Orang Mukmin', ayat: 118 },
  24: { latin: 'An-Nur', arabic: 'النُّور', meaning: 'Cahaya', ayat: 64 },
  25: { latin: 'Al-Furqan', arabic: 'الفُرْقَان', meaning: 'Pembeda', ayat: 77 },
  26: { latin: "Asy-Syu'ara'", arabic: 'الشُّعَرَاء', meaning: 'Para Penyair', ayat: 227 },
  27: { latin: 'An-Naml', arabic: 'النَّمْل', meaning: 'Semut', ayat: 93 },
  28: { latin: 'Al-Qasas', arabic: 'القَصَص', meaning: 'Kisah-Kisah', ayat: 88 },
  29: { latin: "Al-'Ankabut", arabic: 'العَنْكَبُوت', meaning: 'Laba-Laba', ayat: 69 },
  30: { latin: 'Ar-Rum', arabic: 'الرُّوم', meaning: 'Bangsa Romawi', ayat: 60 },
  31: { latin: 'Luqman', arabic: 'لُقْمَان', meaning: 'Luqman', ayat: 34 },
  32: { latin: 'As-Sajdah', arabic: 'السَّجْدَة', meaning: 'Sujud', ayat: 30 },
  33: { latin: 'Al-Ahzab', arabic: 'الأَحْZَاب', meaning: 'Golongan Bersekutu', ayat: 73 },
  34: { latin: "Saba'", arabic: 'سَبَأ', meaning: "Kaum Saba'", ayat: 54 },
  35: { latin: 'Fatir', arabic: 'فَاطِر', meaning: 'Pencipta', ayat: 45 },
  36: { latin: 'Ya-Sin', arabic: 'يس', meaning: 'Yaasiin', ayat: 83 },
  37: { latin: 'As-Saffat', arabic: 'الصَّافَّات', meaning: 'Barisan-Barisan', ayat: 182 },
  38: { latin: 'Sad', arabic: 'ص', meaning: 'Shaad', ayat: 88 },
  39: { latin: 'Az-Zumar', arabic: 'الزُّمَر', meaning: 'Rombongan', ayat: 75 },
  40: { latin: 'Ghafir', arabic: 'غَافِر', meaning: 'Maha Pengampun', ayat: 85 },
  41: { latin: 'Fussilat', arabic: 'فُصِّلَت', meaning: 'Yang Dijelaskan', ayat: 54 },
  42: { latin: 'Asy-Syura', arabic: 'الشُّورَى', meaning: 'Musyawarah', ayat: 53 },
  43: { latin: 'Az-Zukhruf', arabic: 'الزُّخْرُف', meaning: 'Perhiasan', ayat: 89 },
  44: { latin: 'Ad-Dukhan', arabic: 'الدُّخَان', meaning: 'Kabut', ayat: 59 },
  45: { latin: 'Al-Jasiyah', arabic: 'الجَاثِيَة', meaning: 'Yang Berlutut', ayat: 37 },
  46: { latin: 'Al-Ahqaf', arabic: 'الأَحْقَاف', meaning: 'Bukit-Bukit Pasir', ayat: 35 },
  47: { latin: 'Muhammad', arabic: 'مُحَمَّد', meaning: 'Nabi Muhammad', ayat: 38 },
  48: { latin: 'Al-Fath', arabic: 'الفَتْح', meaning: 'Kemenangan', ayat: 29 },
  49: { latin: 'Al-Hujurat', arabic: 'الحُجُرَات', meaning: 'Kamar-Kamar', ayat: 18 },
  50: { latin: 'Qaf', arabic: 'ق', meaning: 'Qaaf', ayat: 45 },
  51: { latin: 'Az-Zariyat', arabic: 'الذَّارِيَات', meaning: 'Angin Yang Menerbangkan', ayat: 60 },
  52: { latin: 'At-Tur', arabic: 'الطُّور', meaning: 'Bukit', ayat: 49 },
  53: { latin: 'An-Najm', arabic: 'النَّجْم', meaning: 'Bintang', ayat: 62 },
  54: { latin: 'Al-Qamar', arabic: 'القَمَر', meaning: 'Bulan', ayat: 55 },
  55: { latin: 'Ar-Rahman', arabic: 'الرَّحْمَن', meaning: 'Yang Maha Pemurah', ayat: 78 },
  56: { latin: "Al-Waqi'ah", arabic: 'الوَاقِعَة', meaning: 'Hari Kiamat', ayat: 96 },
  57: { latin: 'Al-Hadid', arabic: 'الحَدِيد', meaning: 'Besi', ayat: 29 },
  58: { latin: 'Al-Mujadilah', arabic: 'المُجَادِلَة', meaning: 'Wanita Yang Mengajukan Gugatan', ayat: 22 },
  59: { latin: 'Al-Hasyr', arabic: 'الحَشْر', meaning: 'Pengusiran', ayat: 24 },
  60: { latin: 'Al-Mumtahanah', arabic: 'المُمْتَحَنَة', meaning: 'Wanita Yang Diuji', ayat: 13 },
  61: { latin: 'As-Saff', arabic: 'الصَّفّ', meaning: 'Barisan', ayat: 14 },
  62: { latin: "Al-Jumu'ah", arabic: 'Jumu\'ah', meaning: "Hari Jum'at", ayat: 11 },
  63: { latin: 'Al-Munafiqun', arabic: 'المُنَافِقُون', meaning: 'Orang-Orang Munafik', ayat: 11 },
  64: { latin: 'At-Taghabun', arabic: 'التَّغَابُن', meaning: 'Hari Dinampakkan Kesalahan', ayat: 18 },
  65: { latin: 'At-Talaq', arabic: 'الطَّلاَق', meaning: 'Talak', ayat: 12 },
  66: { latin: 'At-Tahrim', arabic: 'التَّحْرِيم', meaning: 'Mengharamkan', ayat: 12 },
  67: { latin: 'Al-Mulk', arabic: 'المُلْك', meaning: 'Kerajaan', ayat: 30 },
  68: { latin: 'Al-Qalam', arabic: 'القَلَم', meaning: 'Pena', ayat: 52 },
  69: { latin: 'Al-Haqqah', arabic: 'الحَاقَّة', meaning: 'Hari Kiamat', ayat: 52 },
  70: { latin: "Al-Ma'arij", arabic: 'المَعَارِج', meaning: 'Tempat Naik', ayat: 44 },
  71: { latin: 'Nuh', arabic: 'نُوح', meaning: 'Nabi Nuh', ayat: 28 },
  72: { latin: 'Al-Jinn', arabic: 'الجِنّ', meaning: 'Jin', ayat: 28 },
  73: { latin: 'Al-Muzzammil', arabic: 'المُزَّمِّل', meaning: 'Orang Yang Berselimut', ayat: 20 },
  74: { latin: 'Al-Muddassir', arabic: 'المُدَّثِّر', meaning: 'Orang Yang Berkemul', ayat: 56 },
  75: { latin: 'Al-Qiyamah', arabic: 'القِيَامَة', meaning: 'Hari Kiamat', ayat: 40 },
  76: { latin: 'Al-Insan', arabic: 'الإِنْسَان', meaning: 'Manusia', ayat: 31 },
  77: { latin: 'Al-Mursalat', arabic: 'المُرْسَلاَت', meaning: 'Malaikat-Malaikat Yang Diutus', ayat: 50 },
  78: { latin: "An-Naba'", arabic: 'النَّبَأ', meaning: 'Berita Besar', ayat: 40 },
  79: { latin: "An-Nazi'at", arabic: 'النَّازِعَات', meaning: 'Malaikat-Malaikat Yang Mencabut', ayat: 46 },
  80: { latin: "'Abasa", arabic: 'عَبَسَ', meaning: 'Ia Bermuka Masam', ayat: 42 },
  81: { latin: 'At-Takwir', arabic: 'التَّكْوِير', meaning: 'Menggulung', ayat: 29 },
  82: { latin: 'Al-Infitar', arabic: 'الإِنْفِطَار', meaning: 'Terbelah', ayat: 19 },
  83: { latin: 'Al-Mutaffifin', arabic: 'المُطَفِّفِين', meaning: 'Orang-Orang Yang Curang', ayat: 36 },
  84: { latin: 'Al-Insyiqaq', arabic: 'الإِنْشِقَاق', meaning: 'Terbelah', ayat: 25 },
  85: { latin: 'Al-Buruj', arabic: 'البُرُوج', meaning: 'Gugusan Bintang', ayat: 22 },
  86: { latin: 'At-Tariq', arabic: 'الطَّارِق', meaning: 'Yang Datang Di Malam Hari', ayat: 17 },
  87: { latin: "Al-A'la", arabic: 'الأَعْلَى', meaning: 'Yang Maha Tinggi', ayat: 19 },
  88: { latin: 'Al-Ghasyiyah', arabic: 'الغَاشِيَة', meaning: 'Hari Pembalasan', ayat: 26 },
  89: { latin: 'Al-Fajr', arabic: 'الفَجْر', meaning: 'Fajar', ayat: 30 },
  90: { latin: 'Al-Balad', arabic: 'البَلَد', meaning: 'Negeri', ayat: 20 },
  91: { latin: 'Asy-Syams', arabic: 'الشَّمْس', meaning: 'Matahari', ayat: 15 },
  92: { latin: 'Al-Lail', arabic: 'اللَّيْل', meaning: 'Malam', ayat: 21 },
  93: { latin: 'Ad-Duha', arabic: 'الضُّحَى', meaning: 'Waktu Dhuha', ayat: 11 },
  94: { latin: 'Al-Insyirah', arabic: 'الشَّرْح', meaning: 'Lapang', ayat: 8 },
  95: { latin: 'At-Tin', arabic: 'التِّين', meaning: 'Buah Tin', ayat: 8 },
  96: { latin: "Al-'Alaq", arabic: 'العَلَق', meaning: 'Segumpal Darah', ayat: 19 },
  97: { latin: 'Al-Qadr', arabic: 'القَدْر', meaning: 'Kemuliaan', ayat: 5 },
  98: { latin: 'Al-Bayyinah', arabic: 'البَيِّنَة', meaning: 'Pembuktian', ayat: 8 },
  99: { latin: 'Az-Zalzalah', arabic: 'الزَّلْزَلَة', meaning: 'Keguncangan', ayat: 8 },
  100: { latin: "Al-'Adiyat", arabic: 'العَادِيَات', meaning: 'Kuda Perang Yang Berlari Kencang', ayat: 11 },
  101: { latin: "Al-Qari'ah", arabic: 'القَارِعَة', meaning: 'Hari Kiamat', ayat: 11 },
  102: { latin: 'At-Takasur', arabic: 'التَّكَاثُر', meaning: 'Bermewah-Mewahan', ayat: 8 },
  103: { latin: "Al-'Asr", arabic: 'العَصْر', meaning: 'Masa', ayat: 3 },
  104: { latin: 'Al-Humazah', arabic: 'الهُمَزَة', meaning: 'Pengumpat', ayat: 9 },
  105: { latin: 'Al-Fil', arabic: 'الفِيل', meaning: 'Gajah', ayat: 5 },
  106: { latin: 'Quraisy', arabic: 'قُرَيْش', meaning: 'Suku Quraisy', ayat: 4 },
  107: { latin: "Al-Ma'un", arabic: 'المَاعُون', meaning: 'Barang-Barang Yang Berguna', ayat: 7 },
  108: { latin: 'Al-Kausar', arabic: 'الكَوْثَر', meaning: 'Nikmat Yang Banyak', ayat: 3 },
  109: { latin: 'Al-Kafirun', arabic: 'الكَافِرُون', meaning: 'Orang-Orang Kafir', ayat: 6 },
  110: { latin: 'An-Nasr', arabic: 'النَّصْر', meaning: 'Pertolongan', ayat: 3 },
  111: { latin: 'Al-Lahab', arabic: 'المَسَد', meaning: 'Gejolak Api', ayat: 5 },
  112: { latin: 'Al-Ikhlas', arabic: 'الإِخْلاَص', meaning: 'Ikhlas', ayat: 4 },
  113: { latin: 'Al-Falaq', arabic: 'الفَلَق', meaning: 'Waktu Subuh', ayat: 5 },
  114: { latin: 'An-Nas', arabic: 'النَّاس', meaning: 'Manusia', ayat: 6 },
};

export function getChapterName(chapterNumber) {
  if (!chapterNumber) return '';
  const num = Number(chapterNumber);
  return CHAPTER_DETAILS[num]?.latin || `Surah ${num}`;
}
